### ISSUE TITLE
Problem with hadd if job is split into too many files. For example, in this case ttbar was split into ~2k files.

### ISSUE THREAD

**Issue by mstoev** [dgonzal/SFrameBatch#34]
Traceback (most recent call last):
  File "/nfs/dust/cms/user/mstoev/SFrameBatch/sframe_batch.py", line 196, in <module>
    status = SFrameBatchMain(sys.argv[1:])
  File "/nfs/dust/cms/user/mstoev/SFrameBatch/sframe_batch.py", line 173, in SFrameBatchMain
    manager.merge_files(cycle.OutputDirectory,nameOfCycle,cycle.Cycle_InputData)
  File "/nfs/dust/cms/user/mstoev/SFrameBatch/Manager.py", line 338, in merge_files
    self.merge.merge(OutputDirectory,nameOfCycle,self.subInfo,self.workdir,InputData)
  File "/nfs/dust/cms/user/mstoev/SFrameBatch/Manager.py", line 377, in merge
    self.active_process.append(add_histos(OutputDirectory,nameOfCycle+'.'+process.data_type+'.'+process.name,process.numberOfFiles,workdir,OutputTreeName,self.onlyhist))
  File "/nfs/dust/cms/user/mstoev/SFrameBatch/batch_classes.py", line 114, in add_histos
    proc = Popen([command_string+directory+name+'.root'+string], shell=True,stdout=PIPE)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/subprocess.py", line 709, in **init**
    errread, errwrite)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long

**Comment by dgonzal** [comment]
Should be solved in cef9e25 .
New limit should be beyond any possible usage. Pls think first and don't exaggerate the number of jobs.
